_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batchSize:
    value: 16
beta:
    value: 80
betas:
    value:
        - 0.9
        - 0.999
delta:
    value: 1
device:
    value: cuda
epochs:
    value: 300
gamma:
    value: 5
learningRate:
    value: 0.001
lrDecay:
    value: 0.99
nll:
    value: true
optimizer:
    value: adam
weightDecay:
    value: 0.0001
